# Generated by Django 3.2.23 on 2023-11-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='SupportLocations',
            name='slug',
            field=models.SlugField(default='chester', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
