# Generated by Django 3.2.23 on 2023-11-22 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0002_supportlocations_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportlocations',
            name='slug',
        ),
    ]
