# Generated by Django 3.2.23 on 2023-11-22 22:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0003_remove_supportlocations_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('achievement_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('achievement_name', models.CharField(max_length=100, unique=True)),
                ('achievement_icon', models.ImageField(default='../default-pic_ls0v0g.png', upload_to='images/')),
                ('achievement_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Diaries',
            },
        ),
    ]
