# Generated by Django 3.2.23 on 2023-11-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0004_achievements_diary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportlocations',
            name='contact_email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='supportlocations',
            name='contact_number',
            field=models.CharField(max_length=200),
        ),
    ]
