# Generated by Django 4.2.7 on 2023-11-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0006_diary_mood_diary_sleep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='sleep',
        ),
    ]
