# Generated by Django 4.2.7 on 2023-11-24 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mood_tracker', '0006_achievements_achievement_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={},
        ),
        migrations.AddField(
            model_name='diary',
            name='owner',
            field=models.ForeignKey(blank=True, default='001', on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
