# Generated by Django 4.2.7 on 2023-11-24 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mood_tracker', '0007_alter_diary_options_diary_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name_plural': 'Diaries'},
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='achievement_user',
        ),
        migrations.AddField(
            model_name='achievements',
            name='achievement_user',
            field=models.ForeignKey(blank=True, default='001', on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
