# Generated by Django 4.2.7 on 2023-11-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0007_remove_diary_mood_remove_diary_sleep'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='mood',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diary',
            name='sleep',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
