# Generated by Django 4.2.7 on 2023-11-25 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mood_tracker', '0008_diary_mood_diary_sleep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='achievement_name',
            field=models.CharField(max_length=100),
        ),
    ]
